### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Kainarx** [mr258876/Project_Vision_L#1]
您好，我遇到了一个问题，如果不焊RT9033，按住开关2s，ec190707的输出会从低电平变成高电平，但是焊了RT9033后，无论按多久开关，ec190707的输出，9033的EN脚都是低电平，只有短接EN和VBAT，同时按住开关2s，然后取消短接，EN才能变成高电平，请问您有遇到过吗

**Comment by mr258876** [comment]
是不是没有焊接SD卡旁边的跳线？

**Comment by mr258876** [comment]
焊上RT9033没有输出的话大概率是焊接有问题。RT9033有短路保护，在短路的情况下不会输出，同时也会将EN拉低。我之前也遇到过类似的情况，重新焊接后恢复正常。

**Comment by Kainarx** [comment]
焊接是没问题的，接电池功能正常，单纯用usb供电就是这种情况了

**Comment by mr258876** [comment]
我还是觉得有少许连锡的可能性。不过接上电池没问题的话就接上电池用吧😂

**Comment by Kainarx** [comment]
因为连着5块板都是这个问题，而且我还是smt的，不过先这样用着，非常感谢！

**Comment by mr258876** [comment]
多谢支持！如果没有其他问题的话issue我就先关闭了，使用过程中遇到bug还请反馈。
p.s. 原来这个project真的有人看呐
