### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by qzrs1996** [mr258876/Project_Vision_L#2]
请问大佬是如何编译的，我自己尝试老是失败

**Comment by mr258876** [comment]
请问编译输出的错误是什么呢？如果可以的话请提供编译日志以帮助定位问题。

**Comment by qzrs1996** [comment]
> 请问编译输出的错误是什么呢？如果可以的话请提供编译日志以帮助定位问题。

src/The_Vision_L.cpp: In function 'void cb_switchToVideoScreen()':
src/The_Vision_L.cpp:505:26: warning: missing initializer for member 'esp_timer_create_args_t::arg' [-Wmissing-field-initializers]
       .name = "resinCalc"};
                          ^
src/The_Vision_L.cpp:505:26: warning: missing initializer for member 'esp_timer_create_args_t::dispatch_method' [-Wmissing-field-initializers]
src/The_Vision_L.cpp:505:26: warning: missing initializer for member 'esp_timer_create_args_t::skip_unhandled_events' [-Wmissing-field-initializers]
src/The_Vision_L.cpp: In function 'void hardwareSetup(void*)':
src/The_Vision_L.cpp:616:22: error: 'lv_qrcode_create' was not declared in this scope
       lv_obj_t *qr = lv_qrcode_create(ui_StartupScreen, 100, lv_color_black(), lv_color_white());
                      ^~~~~~~~~~~~~~~~
src/The_Vision_L.cpp:616:22: note: suggested alternative: 'lv_arc_create'
       lv_obj_t *qr = lv_qrcode_create(ui_StartupScreen, 100, lv_color_black(), lv_color_white());
                      ^~~~~~~~~~~~~~~~
                      lv_arc_create
src/The_Vision_L.cpp:620:7: error: 'lv_qrcode_update' was not declared in this scope
       lv_qrcode_update(qr, data, strlen(data));
       ^~~~~~~~~~~~~~~~
Compiling .pio\build\esp32dev\src\assets\ui_img_Resin.o
src/The_Vision_L.cpp:620:7: note: suggested alternative: 'lv_arc_create'
       lv_qrcode_update(qr, data, strlen(data));
       ^~~~~~~~~~~~~~~~
       lv_arc_create
src/The_Vision_L.cpp:645:17: warning: unused variable 'mbox' [-Wunused-variable]
       lv_obj_t *mbox;
                 ^~~~
Compiling .pio\build\esp32dev\src\assets\ui_img_Transformer.o
Compiling .pio\build\esp32dev\src\assets\ui_img_back.o
*** [.pio\build\esp32dev\src\The_Vision_L.o] Error 1

**Comment by qzrs1996** [comment]
> 

lv_qrcode_create  lv_qrcode_update 这2个报错，我看了是二维码生成的，我查了网上，是需要加载另一个库吗 ？https://github.com/lvgl/lv_lib_qrcode.git

**Comment by mr258876** [comment]
是lvgl的配置文件问题，之前我把lv_conf.h放库文件夹里没加进来。我看看怎么把lv_conf.h放进项目里

**Comment by qzrs1996** [comment]
> 是lvgl的配置文件问题，之前我把lv_conf.h放库文件夹里没加进来。我看看怎么把lv_conf.h放进项目里

好的，麻烦你了， 或者可以直接放根目录就好

**Comment by mr258876** [comment]
问题已修复，请通过 `git fetch` 同步代码并重新编译。

**Comment by qzrs1996** [comment]
> 问题已修复，请通过 `git fetch` 同步代码并重新编译。

OK OK
