### ISSUE TITLE
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"

### ISSUE THREAD

**Issue by qzrs1996** [mr258876/Project_Vision_L#3]
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_font_HanyiWenhei16.c:12:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_font_HanyiWenhei16ZhHans.c:7:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_font_HanyiWenhei24.c:12:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Expeditions.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_font_HanyiWenhei24ZhHans.c:7:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Homecoin.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Horoscope03.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Horoscope04.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Horoscope06.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_Horoscope05.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/assets/ui_img_HoroscopeBg.c:1:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
src/Hoyoverse.cpp: In member function 'HoyoverseClient_result_t HoyoverseClient::syncDailyNote(Notedata*)':
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::host' [-Wmissing-field-initializers]
     };
     ^
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::port' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::username' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::password' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::auth_type' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::path' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::query' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::cert_len' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_cert_pem' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_cert_len' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_key_pem' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_key_len' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_key_password' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::client_key_password_len' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::timeout_ms' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::disable_auto_redirect' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::max_redirection_count' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::max_authorization_retries' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::event_handler' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::transport_type' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::buffer_size' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::user_data' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::is_async' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::use_global_ca_store' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::skip_cert_common_name_check' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::crt_bundle_attach' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::keep_alive_idle' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::keep_alive_interval' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::keep_alive_count' [-Wmissing-field-initializers]
src/Hoyoverse.cpp:133:5: warning: missing initializer for member 'esp_http_client_config_t::if_name' [-Wmissing-field-initializers]
In file included from lib/lvgl/src/hal/../draw/../misc/lv_style.h:19,
                 from lib/lvgl/src/hal/../draw/lv_draw.h:18,
                 from lib/lvgl/src/hal/lv_hal_disp.h:21,
                 from lib/lvgl/src/hal/lv_hal.h:16,
                 from lib/lvgl/lvgl.h:33,
                 from src/The_Vision_L.cpp:12:
lib/lvgl/src/hal/../draw/../misc/lv_color.h:27:2: error: #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
 #error "LV_COLOR_SCREEN_TRANSP requires LV_COLOR_DEPTH == 32. Set it in lv_conf.h"
  ^~~~~
*** [.pio\build\esp32dev\src\assets\ui_img_Expeditions.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_font_HanyiWenhei24ZhHans.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_img_Horoscope03.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_img_Horoscope05.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_font_HanyiWenhei24.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_font_HanyiWenhei16ZhHans.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_font_HanyiWenhei16.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_img_Homecoin.o] Error 1
src/The_Vision_L.cpp: In function 'void cb_switchToVideoScreen()':
src/The_Vision_L.cpp:601:26: warning: missing initializer for member 'esp_timer_create_args_t::arg' [-Wmissing-field-initializers]
       .name = "resinCalc"};
                          ^
src/The_Vision_L.cpp:601:26: warning: missing initializer for member 'esp_timer_create_args_t::dispatch_method' [-Wmissing-field-initializers]
src/The_Vision_L.cpp:601:26: warning: missing initializer for member 'esp_timer_create_args_t::skip_unhandled_events' [-Wmissing-field-initializers]
src/The_Vision_L.cpp: In function 'void hardwareSetup(void*)':
src/The_Vision_L.cpp:728:17: warning: unused variable 'mbox' [-Wunused-variable]
       lv_obj_t *mbox;
                 ^~~~
*** [.pio\build\esp32dev\src\assets\ui_img_HoroscopeBg.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_img_Horoscope04.o] Error 1
*** [.pio\build\esp32dev\src\assets\ui_img_Horoscope06.o] Error 1
*** [.pio\build\esp32dev\src\The_Vision_L.o] Error 1

**Comment by qzrs1996** [comment]
网上实在是找不到解决方法，按照报错上面修改也没用。 捂脸

**Comment by mr258876** [comment]
espidf的锅，需要在编译时加参数忽略将该警告视为错误。问题已修复，请同步代码并重新编译。

**Comment by mr258876** [comment]
另外请检查lvgl版本，在lvgl8.3中启用透明度功能是不需要将色深设置为32位的
